; Proyecto 1 - Seminario de Mecatrónica
; Robot con ruedas + caparazón 3D + L9110S + sensor ultrasónico
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
